# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    vim.toml                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: chenxu <chenxu@mail.ustc.edu.cn>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/29 01:13:40 by chenxu            #+#    #+#              #
#    Updated: 2024/05/06 20:12:05 by chenxu           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

[vim]
any = true

[jit]
any = true

[cx]
any = true,
